Documentation
Misfiy/RueI pull request #3
Opened 2024-05-28 15:58 UTC by 6hundred9

Made it a draft for probably no reason at all

2024-05-28 17:56 UTC, 6hundred9 commented
alr

2024-05-28 17:56 UTC, 6hundred9 commented
you can just ping me in discord yk

2024-05-28 18:00 UTC, Misfiy requested changes

2024-05-28 18:00 UTC, Misfiy commented on RueI/index.md
> +If you wish to start making plugins using RueI, most of the documentation will be here and in [the RueI site](https://ruemena.github.io/RueI/), if you have any questions you can ask it in [the EXILED
This leads to the same page

2024-05-28 18:00 UTC, 6hundred9 commented on RueI/index.md
> +If you wish to start making plugins using RueI, most of the documentation will be here and in [the RueI site](https://ruemena.github.io/RueI/), if you have any questions you can ask it in [the EXILED
oh

2024-05-29 09:59 UTC, 6hundred9 commented
@Misfiy tell me stuff to add to docs

2024-05-29 14:48 UTC, merged